/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/matches/{match_id}": {
    /** Match data */
    get: {
      parameters: {
        path: {
          match_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** The ID number of the match assigned by Valve */
            match_id?: number;
            /** Bitmask. An integer that represents a binary of which barracks are still standing. 63 would mean all barracks still stand at the end of the game. */
            barracks_status_dire?: number;
            /** Bitmask. An integer that represents a binary of which barracks are still standing. 63 would mean all barracks still stand at the end of the game. */
            barracks_status_radiant?: number;
            /** Array containing information on the chat of the game */
            chat?: {
              /** Time in seconds at which the message was said */
              time?: number;
              /** Name of the player who sent the message */
              unit?: string;
              /** The message the player sent */
              key?: string;
              /** slot */
              slot?: number;
              /** Which slot the player is in. 0-127 are Radiant, 128-255 are Dire */
              player_slot?: number;
            }[];
            /** cluster */
            cluster?: number;
            /** cosmetics */
            cosmetics?: { [key: string]: unknown };
            /** Final score for Dire (number of kills on Radiant) */
            dire_score?: number;
            /** draft_timings */
            draft_timings?: {
              /** order */
              order?: number;
              /** pick */
              pick?: boolean;
              /** active_team */
              active_team?: number;
              /** The ID value of the hero played */
              hero_id?: number;
              /** Which slot the player is in. 0-127 are Radiant, 128-255 are Dire */
              player_slot?: number;
              /** extra_time */
              extra_time?: number;
              /** total_time_taken */
              total_time_taken?: number;
            }[];
            /** Duration of the game in seconds */
            duration?: number;
            /** engine */
            engine?: number;
            /** Time in seconds at which first blood occurred */
            first_blood_time?: number;
            /** Integer corresponding to game mode played. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/game_mode.json */
            game_mode?: number;
            /** Number of human players in the game */
            human_players?: number;
            /** leagueid */
            leagueid?: number;
            /** Integer corresponding to lobby type of match. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/lobby_type.json */
            lobby_type?: number;
            /** match_seq_num */
            match_seq_num?: number;
            /** Number of negative votes the replay received in the in-game client */
            negative_votes?: number;
            /** objectives */
            objectives?: { [key: string]: unknown };
            /** Object containing information on the draft. Each pick/ban contains a boolean relating to whether the choice is a pick or a ban, the hero ID, the team the picked or banned it, and the order. */
            picks_bans?: { [key: string]: unknown };
            /** Number of positive votes the replay received in the in-game client */
            positive_votes?: number;
            /** Array of the Radiant gold advantage at each minute in the game. A negative number means that Radiant is behind, and thus it is their gold disadvantage. */
            radiant_gold_adv?: { [key: string]: unknown };
            /** Final score for Radiant (number of kills on Radiant) */
            radiant_score?: number;
            /** Boolean indicating whether Radiant won the match */
            radiant_win?: boolean;
            /** Array of the Radiant experience advantage at each minute in the game. A negative number means that Radiant is behind, and thus it is their experience disadvantage. */
            radiant_xp_adv?: { [key: string]: unknown };
            /** The Unix timestamp at which the game started */
            start_time?: number;
            /** teamfights */
            teamfights?: { [key: string]: unknown };
            /** Bitmask. An integer that represents a binary of which Dire towers are still standing. */
            tower_status_dire?: number;
            /** Bitmask. An integer that represents a binary of which Radiant towers are still standing. */
            tower_status_radiant?: number;
            /** Parse version, used internally by OpenDota */
            version?: number;
            /** replay_salt */
            replay_salt?: number;
            /** series_id */
            series_id?: number;
            /** series_type */
            series_type?: number;
            /** radiant_team */
            radiant_team?: { [key: string]: unknown };
            /** dire_team */
            dire_team?: { [key: string]: unknown };
            /** league */
            league?: { [key: string]: unknown };
            /** Skill bracket assigned by Valve (Normal, High, Very High) */
            skill?: number;
            /** Array of information on individual players */
            players?: {
              /** Match ID */
              match_id?: number;
              /** Which slot the player is in. 0-127 are Radiant, 128-255 are Dire */
              player_slot?: number;
              /** An array describing how abilities were upgraded */
              ability_upgrades_arr?: number[];
              /** Object containing information on how many times the played used their abilities */
              ability_uses?: { [key: string]: unknown };
              /** Object containing information on who the player used their abilities on */
              ability_targets?: { [key: string]: unknown };
              /** Object containing information on how and how much damage the player dealt to other heroes */
              damage_targets?: { [key: string]: unknown };
              /** account_id */
              account_id?: number;
              /** Object containing information on how many and what type of actions the player issued to their hero */
              actions?: { [key: string]: unknown };
              /** Object containing information on additional units the player had under their control */
              additional_units?: { [key: string]: unknown };
              /** Number of assists the player had */
              assists?: number;
              /** Item in backpack slot 0 */
              backpack_0?: number;
              /** Item in backpack slot 1 */
              backpack_1?: number;
              /** Item in backpack slot 2 */
              backpack_2?: number;
              /** Array containing information about buybacks */
              buyback_log?: {
                /** Time in seconds the buyback occurred */
                time?: number;
                /** slot */
                slot?: number;
                /** Which slot the player is in. 0-127 are Radiant, 128-255 are Dire */
                player_slot?: number;
              }[];
              /** Number of camps stacked */
              camps_stacked?: number;
              /** Array containing information about the player's disconnections and reconnections */
              connection_log?: {
                /** Game time in seconds the event ocurred */
                time?: number;
                /** Event that occurred */
                event?: string;
                /** Which slot the player is in. 0-127 are Radiant, 128-255 are Dire */
                player_slot?: number;
              }[];
              /** Number of creeps stacked */
              creeps_stacked?: number;
              /** Object containing information about damage dealt by the player to different units */
              damage?: { [key: string]: unknown };
              /** Object containing information about about the sources of this player's damage to heroes */
              damage_inflictor?: { [key: string]: unknown };
              /** Object containing information about the sources of damage received by this player from heroes */
              damage_inflictor_received?: { [key: string]: unknown };
              /** Object containing information about from whom the player took damage */
              damage_taken?: { [key: string]: unknown };
              /** Number of deaths */
              deaths?: number;
              /** Number of denies */
              denies?: number;
              /** Array containing number of denies at different times of the match */
              dn_t?: number[];
              /** Gold at the end of the game */
              gold?: number;
              /** Gold Per Minute obtained by this player */
              gold_per_min?: number;
              /** Object containing information on how the player gainined gold over the course of the match */
              gold_reasons?: { [key: string]: unknown };
              /** How much gold the player spent */
              gold_spent?: number;
              /** Array containing total gold at different times of the match */
              gold_t?: number[];
              /** Hero Damage Dealt */
              hero_damage?: number;
              /** Hero Healing Done */
              hero_healing?: number;
              /** Object containing information on how many ticks of damages the hero inflicted with different spells and damage inflictors */
              hero_hits?: { [key: string]: unknown };
              /** The ID value of the hero played */
              hero_id?: number;
              /** Item in the player's first slot */
              item_0?: number;
              /** Item in the player's second slot */
              item_1?: number;
              /** Item in the player's third slot */
              item_2?: number;
              /** Item in the player's fourth slot */
              item_3?: number;
              /** Item in the player's fifth slot */
              item_4?: number;
              /** Item in the player's sixth slot */
              item_5?: number;
              /** Object containing information about how many times a player used items */
              item_uses?: { [key: string]: unknown };
              /** Object containing information about the player's killstreaks */
              kill_streaks?: { [key: string]: unknown };
              /** Object containing information about what units the player killed */
              killed?: { [key: string]: unknown };
              /** Object containing information about who killed the player */
              killed_by?: { [key: string]: unknown };
              /** Number of kills */
              kills?: number;
              /** Array containing information on which hero the player killed at what time */
              kills_log?: {
                /** Time in seconds the player killed the hero */
                time?: number;
                /** Hero killed */
                key?: string;
              }[];
              /** Object containing information on lane position */
              lane_pos?: { [key: string]: unknown };
              /** Number of last hits */
              last_hits?: number;
              /** Integer describing whether or not the player left the game. 0: didn't leave. 1: left safely. 2+: Abandoned */
              leaver_status?: number;
              /** Level at the end of the game */
              level?: number;
              /** Array describing last hits at each minute in the game */
              lh_t?: number[];
              /** life_state */
              life_state?: { [key: string]: unknown };
              /** Object with information on the highest damage instance the player inflicted */
              max_hero_hit?: { [key: string]: unknown };
              /** Object with information on the number of the number of multikills the player had */
              multi_kills?: { [key: string]: unknown };
              /** Object with information on where the player placed observer wards. The location takes the form (outer number, inner number) and are from ~64-192. */
              obs?: { [key: string]: unknown };
              /** obs_left_log */
              obs_left_log?: { [key: string]: unknown }[];
              /** Object containing information on when and where the player placed observer wards */
              obs_log?: { [key: string]: unknown }[];
              /** Total number of observer wards placed */
              obs_placed?: number;
              /** party_id */
              party_id?: number;
              /** Array describing permanent buffs the player had at the end of the game. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/permanent_buffs.json */
              permanent_buffs?: { [key: string]: unknown }[];
              /** Total number of pings */
              pings?: number;
              /** Object containing information on the items the player purchased */
              purchase?: { [key: string]: unknown };
              /** Object containing information on when items were purchased */
              purchase_log?: {
                /** Time in seconds the item was bought */
                time?: number;
                /** String item ID */
                key?: string;
                /** Integer amount of charges */
                charges?: number;
              }[];
              /** Number of runes picked up */
              rune_pickups?: number;
              /** Object with information about which runes the player picked up */
              runes?: { [key: string]: number };
              /** Array with information on when runes were picked up */
              runes_log?: {
                /** Time in seconds rune picked up */
                time?: number;
                /** key */
                key?: number;
              }[];
              /** Object with information on where sentries were placed. The location takes the form (outer number, inner number) and are from ~64-192. */
              sen?: { [key: string]: unknown };
              /** Array containing information on when and where the player placed sentries */
              sen_left_log?: { [key: string]: unknown }[];
              /** Array with information on when and where sentries were placed by the player */
              sen_log?: { [key: string]: unknown }[];
              /** How many sentries were placed by the player */
              sen_placed?: number;
              /** Total stun duration of all stuns by the player */
              stuns?: number;
              /** Time in seconds corresponding to the time of entries of other arrays in the match. */
              times?: number[];
              /** Total tower damage done by the player */
              tower_damage?: number;
              /** Experience Per Minute obtained by the player */
              xp_per_min?: number;
              /** Object containing information on the sources of this player's experience */
              xp_reasons?: { [key: string]: unknown };
              /** Experience at each minute of the game */
              xp_t?: number[];
              /** personaname */
              personaname?: string;
              /** name */
              name?: string;
              /** Time of player's last login */
              last_login?: string;
              /** Boolean indicating whether Radiant won the match */
              radiant_win?: boolean;
              /** Start time of the match in seconds since 1970 */
              start_time?: number;
              /** Duration of the game in seconds */
              duration?: number;
              /** cluster */
              cluster?: number;
              /** Integer corresponding to lobby type of match. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/lobby_type.json */
              lobby_type?: number;
              /** Integer corresponding to game mode played. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/game_mode.json */
              game_mode?: number;
              /** Integer representing the patch the game was played on */
              patch?: number;
              /** Integer corresponding to the region the game was played on */
              region?: number;
              /** Boolean for whether or not the player is on Radiant */
              isRadiant?: boolean;
              /** Binary integer representing whether or not the player won */
              win?: number;
              /** Binary integer representing whether or not the player lost */
              lose?: number;
              /** Total gold at the end of the game */
              total_gold?: number;
              /** Total experience at the end of the game */
              total_xp?: number;
              /** Number of kills per minute */
              kills_per_min?: number;
              /** kda */
              kda?: number;
              /** abandons */
              abandons?: number;
              /** Total number of neutral creeps killed */
              neutral_kills?: number;
              /** Total number of tower kills the player had */
              tower_kills?: number;
              /** Total number of courier kills the player had */
              courier_kills?: number;
              /** Total number of lane creeps killed by the player */
              lane_kills?: number;
              /** Total number of heroes killed by the player */
              hero_kills?: number;
              /** Total number of observer wards killed by the player */
              observer_kills?: number;
              /** Total number of sentry wards killed by the player */
              sentry_kills?: number;
              /** Total number of roshan kills (last hit on roshan) the player had */
              roshan_kills?: number;
              /** Total number of Necronomicon creeps killed by the player */
              necronomicon_kills?: number;
              /** Total number of Ancient creeps killed by the player */
              ancient_kills?: number;
              /** Total number of buyback the player used */
              buyback_count?: number;
              /** Number of observer wards used */
              observer_uses?: number;
              /** Number of sentry wards used */
              sentry_uses?: number;
              /** lane_efficiency */
              lane_efficiency?: number;
              /** lane_efficiency_pct */
              lane_efficiency_pct?: number;
              /** Integer referring to which lane the hero laned in */
              lane?: number;
              /** lane_role */
              lane_role?: number;
              /** Boolean referring to whether or not the player roamed */
              is_roaming?: boolean;
              /** Object with information on when the player last purchased an item */
              purchase_time?: { [key: string]: unknown };
              /** Object with information on when the player first puchased an item */
              first_purchase_time?: { [key: string]: unknown };
              /** Object with information on whether or not the item won */
              item_win?: { [key: string]: unknown };
              /** Object containing binary integers the tell whether the item was purchased by the player (note: this is always 1) */
              item_usage?: { [key: string]: unknown };
              /** Total number of TP scrolls purchased by the player */
              purchase_tpscroll?: { [key: string]: unknown };
              /** Actions per minute */
              actions_per_min?: number;
              /** life_state_dead */
              life_state_dead?: number;
              /** The rank tier of the player. Tens place indicates rank, ones place indicates stars. */
              rank_tier?: number;
              /** cosmetics */
              cosmetics?: number[];
              /** Object containing information on certain benchmarks like GPM, XPM, KDA, tower damage, etc */
              benchmarks?: { [key: string]: unknown };
            }[];
            /** Information on the patch version the game is played on */
            patch?: number;
            /** Integer corresponding to the region the game was played on */
            region?: number;
            /** Word counts of the all chat messages in the player's games */
            all_word_counts?: { [key: string]: unknown };
            /** Word counts of the player's all chat messages */
            my_word_counts?: { [key: string]: unknown };
            /** Maximum gold advantage of the player's team if they lost the match */
            throw?: number;
            /** Maximum gold disadvantage of the player's team if they won the match */
            comeback?: number;
            /** Maximum gold disadvantage of the player's team if they lost the match */
            loss?: number;
            /** Maximum gold advantage of the player's team if they won the match */
            win?: number;
            /** replay_url */
            replay_url?: string;
          };
        };
      };
    };
  };
  "/playersByRank": {
    /** Players ordered by rank/medal tier */
    get: {
      parameters: {};
      responses: {
        /** Success */
        200: {
          schema: {
            /** account_id */
            account_id?: number;
            /** Integer indicating the rank/medal of the player */
            rank_tier?: number;
            /** Indicates if we were unable to fetch full history for this player due to privacy settings */
            fh_unavailable?: boolean;
          };
        };
      };
    };
  };
  "/players/{account_id}": {
    /** Player data */
    get: {
      parameters: {
        path: {
          /** Steam32 account ID */
          account_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** tracked_until */
            tracked_until?: string;
            /** solo_competitive_rank */
            solo_competitive_rank?: string;
            /** competitive_rank */
            competitive_rank?: string;
            /** rank_tier */
            rank_tier?: number;
            /** leaderboard_rank */
            leaderboard_rank?: number;
            /** mmr_estimate */
            mmr_estimate?: {
              /** estimate */
              estimate?: number;
              /** stdDev */
              stdDev?: number;
              /** n */
              n?: number;
            };
            /** profile */
            profile?: {
              /** account_id */
              account_id?: number;
              /** personaname */
              personaname?: string;
              /** name */
              name?: string;
              /** Boolean indicating status of current Dota Plus subscription */
              plus?: boolean;
              /** cheese */
              cheese?: number;
              /** steamid */
              steamid?: string;
              /** avatar */
              avatar?: string;
              /** avatarmedium */
              avatarmedium?: string;
              /** avatarfull */
              avatarfull?: string;
              /** profileurl */
              profileurl?: string;
              /** last_login */
              last_login?: string;
              /** loccountrycode */
              loccountrycode?: string;
              /** Boolean indicating if the user contributed to the development of OpenDota */
              is_contributor?: boolean;
            };
          };
        };
      };
    };
  };
  "/players/{account_id}/wl": {
    /** Win/Loss count */
    get: {
      parameters: {
        path: {
          /** Steam32 account ID */
          account_id: number;
        };
        query: {
          /** Number of matches to limit to */
          limit?: number;
          /** Number of matches to offset start by */
          offset?: number;
          /** Whether the player won */
          win?: number;
          /** Patch ID */
          patch?: number;
          /** Game Mode ID */
          game_mode?: number;
          /** Lobby type ID */
          lobby_type?: number;
          /** Region ID */
          region?: number;
          /** Days previous */
          date?: number;
          /** Lane Role ID */
          lane_role?: number;
          /** Hero ID */
          hero_id?: number;
          /** Whether the player was radiant */
          is_radiant?: number;
          /** Account IDs in the match (array) */
          included_account_id?: number;
          /** Account IDs not in the match (array) */
          excluded_account_id?: number;
          /** Hero IDs on the player's team (array) */
          with_hero_id?: number;
          /** Hero IDs against the player's team (array) */
          against_hero_id?: number;
          /** Whether the match was significant for aggregation purposes. Defaults to 1 (true), set this to 0 to return data for non-standard modes/matches. */
          significant?: number;
          /** The minimum number of games played, for filtering hero stats */
          having?: number;
          /** The field to return matches sorted by in descending order */
          sort?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** Number of wins */
            win?: number;
            /** Number of loses */
            lose?: number;
          };
        };
      };
    };
  };
  "/players/{account_id}/recentMatches": {
    /** Recent matches played */
    get: {
      parameters: {
        path: {
          /** Steam32 account ID */
          account_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** Match ID */
            match_id?: number;
            /** Which slot the player is in. 0-127 are Radiant, 128-255 are Dire */
            player_slot?: number;
            /** Boolean indicating whether Radiant won the match */
            radiant_win?: boolean;
            /** Duration of the game in seconds */
            duration?: number;
            /** Integer corresponding to game mode played. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/game_mode.json */
            game_mode?: number;
            /** Integer corresponding to lobby type of match. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/lobby_type.json */
            lobby_type?: number;
            /** The ID value of the hero played */
            hero_id?: number;
            /** Start time of the match in seconds elapsed since 1970 */
            start_time?: number;
            /** version */
            version?: number;
            /** Total kills the player had at the end of the match */
            kills?: number;
            /** Total deaths the player had at the end of the match */
            deaths?: number;
            /** Total assists the player had at the end of the match */
            assists?: number;
            /** Skill bracket assigned by Valve (Normal, High, Very High) */
            skill?: number;
            /** Integer corresponding to which lane the player laned in for the match */
            lane?: number;
            /** lane_role */
            lane_role?: number;
            /** Boolean describing whether or not the player roamed */
            is_roaming?: boolean;
            /** cluster */
            cluster?: number;
            /** Integer describing whether or not the player left the game. 0: didn't leave. 1: left safely. 2+: Abandoned */
            leaver_status?: number;
            /** Size of the players party. If not in a party, will return 1. */
            party_size?: number;
          }[];
        };
      };
    };
  };
  "/players/{account_id}/matches": {
    /** Matches played */
    get: {
      parameters: {
        path: {
          /** Steam32 account ID */
          account_id: number;
        };
        query: {
          /** Number of matches to limit to */
          limit?: number;
          /** Number of matches to offset start by */
          offset?: number;
          /** Whether the player won */
          win?: number;
          /** Patch ID */
          patch?: number;
          /** Game Mode ID */
          game_mode?: number;
          /** Lobby type ID */
          lobby_type?: number;
          /** Region ID */
          region?: number;
          /** Days previous */
          date?: number;
          /** Lane Role ID */
          lane_role?: number;
          /** Hero ID */
          hero_id?: number;
          /** Whether the player was radiant */
          is_radiant?: number;
          /** Account IDs in the match (array) */
          included_account_id?: number;
          /** Account IDs not in the match (array) */
          excluded_account_id?: number;
          /** Hero IDs on the player's team (array) */
          with_hero_id?: number;
          /** Hero IDs against the player's team (array) */
          against_hero_id?: number;
          /** Whether the match was significant for aggregation purposes. Defaults to 1 (true), set this to 0 to return data for non-standard modes/matches. */
          significant?: number;
          /** The minimum number of games played, for filtering hero stats */
          having?: number;
          /** The field to return matches sorted by in descending order */
          sort?: string;
          /** Fields to project (array) */
          project?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** Match ID */
            match_id?: number;
            /** Which slot the player is in. 0-127 are Radiant, 128-255 are Dire */
            player_slot?: number;
            /** Boolean indicating whether Radiant won the match */
            radiant_win?: boolean;
            /** Duration of the game in seconds */
            duration?: number;
            /** Integer corresponding to game mode played. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/game_mode.json */
            game_mode?: number;
            /** Integer corresponding to lobby type of match. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/lobby_type.json */
            lobby_type?: number;
            /** The ID value of the hero played */
            hero_id?: number;
            /** Time the game started in seconds since 1970 */
            start_time?: number;
            /** version */
            version?: number;
            /** Total kills the player had at the end of the game */
            kills?: number;
            /** Total deaths the player had at the end of the game */
            deaths?: number;
            /** Total assists the player had at the end of the game */
            assists?: number;
            /** Skill bracket assigned by Valve (Normal, High, Very High) */
            skill?: number;
            /** Size of the player's party */
            party_size?: number;
            /** heroes (requires ?project=heroes) */
            heroes?: {
              /** Which slot the player is in. 0-127 are Radiant, 128-255 are Dire */
              player_slot?: {
                /** account_id */
                account_id?: number;
                /** The ID value of the hero played */
                hero_id?: number;
                /** Which slot the player is in. 0-127 are Radiant, 128-255 are Dire */
                player_slot?: number;
              };
            };
          }[];
        };
      };
    };
  };
  "/players/{account_id}/heroes": {
    /** Heroes played */
    get: {
      parameters: {
        path: {
          /** Steam32 account ID */
          account_id: number;
        };
        query: {
          /** Number of matches to limit to */
          limit?: number;
          /** Number of matches to offset start by */
          offset?: number;
          /** Whether the player won */
          win?: number;
          /** Patch ID */
          patch?: number;
          /** Game Mode ID */
          game_mode?: number;
          /** Lobby type ID */
          lobby_type?: number;
          /** Region ID */
          region?: number;
          /** Days previous */
          date?: number;
          /** Lane Role ID */
          lane_role?: number;
          /** Hero ID */
          hero_id?: number;
          /** Whether the player was radiant */
          is_radiant?: number;
          /** Account IDs in the match (array) */
          included_account_id?: number;
          /** Account IDs not in the match (array) */
          excluded_account_id?: number;
          /** Hero IDs on the player's team (array) */
          with_hero_id?: number;
          /** Hero IDs against the player's team (array) */
          against_hero_id?: number;
          /** Whether the match was significant for aggregation purposes. Defaults to 1 (true), set this to 0 to return data for non-standard modes/matches. */
          significant?: number;
          /** The minimum number of games played, for filtering hero stats */
          having?: number;
          /** The field to return matches sorted by in descending order */
          sort?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** The ID value of the hero played */
            hero_id?: string;
            /** last_played */
            last_played?: number;
            /** games */
            games?: number;
            /** win */
            win?: number;
            /** with_games */
            with_games?: number;
            /** with_win */
            with_win?: number;
            /** against_games */
            against_games?: number;
            /** against_win */
            against_win?: number;
          }[];
        };
      };
    };
  };
  "/players/{account_id}/peers": {
    /** Players played with */
    get: {
      parameters: {
        path: {
          /** Steam32 account ID */
          account_id: number;
        };
        query: {
          /** Number of matches to limit to */
          limit?: number;
          /** Number of matches to offset start by */
          offset?: number;
          /** Whether the player won */
          win?: number;
          /** Patch ID */
          patch?: number;
          /** Game Mode ID */
          game_mode?: number;
          /** Lobby type ID */
          lobby_type?: number;
          /** Region ID */
          region?: number;
          /** Days previous */
          date?: number;
          /** Lane Role ID */
          lane_role?: number;
          /** Hero ID */
          hero_id?: number;
          /** Whether the player was radiant */
          is_radiant?: number;
          /** Account IDs in the match (array) */
          included_account_id?: number;
          /** Account IDs not in the match (array) */
          excluded_account_id?: number;
          /** Hero IDs on the player's team (array) */
          with_hero_id?: number;
          /** Hero IDs against the player's team (array) */
          against_hero_id?: number;
          /** Whether the match was significant for aggregation purposes. Defaults to 1 (true), set this to 0 to return data for non-standard modes/matches. */
          significant?: number;
          /** The minimum number of games played, for filtering hero stats */
          having?: number;
          /** The field to return matches sorted by in descending order */
          sort?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** account_id */
            account_id?: number;
            /** last_played */
            last_played?: number;
            /** win */
            win?: number;
            /** games */
            games?: number;
            /** with_win */
            with_win?: number;
            /** with_games */
            with_games?: number;
            /** against_win */
            against_win?: number;
            /** against_games */
            against_games?: number;
            /** with_gpm_sum */
            with_gpm_sum?: number;
            /** with_xpm_sum */
            with_xpm_sum?: number;
            /** personaname */
            personaname?: string;
            /** name */
            name?: string;
            /** is_contributor */
            is_contributor?: boolean;
            /** last_login */
            last_login?: string;
            /** avatar */
            avatar?: string;
            /** avatarfull */
            avatarfull?: string;
          }[];
        };
      };
    };
  };
  "/players/{account_id}/pros": {
    /** Pro players played with */
    get: {
      parameters: {
        path: {
          /** Steam32 account ID */
          account_id: number;
        };
        query: {
          /** Number of matches to limit to */
          limit?: number;
          /** Number of matches to offset start by */
          offset?: number;
          /** Whether the player won */
          win?: number;
          /** Patch ID */
          patch?: number;
          /** Game Mode ID */
          game_mode?: number;
          /** Lobby type ID */
          lobby_type?: number;
          /** Region ID */
          region?: number;
          /** Days previous */
          date?: number;
          /** Lane Role ID */
          lane_role?: number;
          /** Hero ID */
          hero_id?: number;
          /** Whether the player was radiant */
          is_radiant?: number;
          /** Account IDs in the match (array) */
          included_account_id?: number;
          /** Account IDs not in the match (array) */
          excluded_account_id?: number;
          /** Hero IDs on the player's team (array) */
          with_hero_id?: number;
          /** Hero IDs against the player's team (array) */
          against_hero_id?: number;
          /** Whether the match was significant for aggregation purposes. Defaults to 1 (true), set this to 0 to return data for non-standard modes/matches. */
          significant?: number;
          /** The minimum number of games played, for filtering hero stats */
          having?: number;
          /** The field to return matches sorted by in descending order */
          sort?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** account_id */
            account_id?: number;
            /** name */
            name?: string;
            /** country_code */
            country_code?: string;
            /** fantasy_role */
            fantasy_role?: number;
            /** team_id */
            team_id?: number;
            /** team_name */
            team_name?: string;
            /** team_tag */
            team_tag?: string;
            /** is_locked */
            is_locked?: boolean;
            /** is_pro */
            is_pro?: boolean;
            /** locked_until */
            locked_until?: number;
            /** steamid */
            steamid?: string;
            /** avatar */
            avatar?: string;
            /** avatarmedium */
            avatarmedium?: string;
            /** avatarfull */
            avatarfull?: string;
            /** profileurl */
            profileurl?: string;
            /** last_login */
            last_login?: string;
            /** full_history_time */
            full_history_time?: string;
            /** cheese */
            cheese?: number;
            /** fh_unavailable */
            fh_unavailable?: boolean;
            /** loccountrycode */
            loccountrycode?: string;
            /** last_played */
            last_played?: number;
            /** win */
            win?: number;
            /** games */
            games?: number;
            /** with_win */
            with_win?: number;
            /** with_games */
            with_games?: number;
            /** against_win */
            against_win?: number;
            /** against_games */
            against_games?: number;
            /** with_gpm_sum */
            with_gpm_sum?: number;
            /** with_xpm_sum */
            with_xpm_sum?: number;
          }[];
        };
      };
    };
  };
  "/players/{account_id}/totals": {
    /** Totals in stats */
    get: {
      parameters: {
        path: {
          /** Steam32 account ID */
          account_id: number;
        };
        query: {
          /** Number of matches to limit to */
          limit?: number;
          /** Number of matches to offset start by */
          offset?: number;
          /** Whether the player won */
          win?: number;
          /** Patch ID */
          patch?: number;
          /** Game Mode ID */
          game_mode?: number;
          /** Lobby type ID */
          lobby_type?: number;
          /** Region ID */
          region?: number;
          /** Days previous */
          date?: number;
          /** Lane Role ID */
          lane_role?: number;
          /** Hero ID */
          hero_id?: number;
          /** Whether the player was radiant */
          is_radiant?: number;
          /** Account IDs in the match (array) */
          included_account_id?: number;
          /** Account IDs not in the match (array) */
          excluded_account_id?: number;
          /** Hero IDs on the player's team (array) */
          with_hero_id?: number;
          /** Hero IDs against the player's team (array) */
          against_hero_id?: number;
          /** Whether the match was significant for aggregation purposes. Defaults to 1 (true), set this to 0 to return data for non-standard modes/matches. */
          significant?: number;
          /** The minimum number of games played, for filtering hero stats */
          having?: number;
          /** The field to return matches sorted by in descending order */
          sort?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** field */
            field?: string;
            /** number */
            n?: number;
            /** sum */
            sum?: number;
          }[];
        };
      };
    };
  };
  "/players/{account_id}/counts": {
    /** Counts in categories */
    get: {
      parameters: {
        path: {
          /** Steam32 account ID */
          account_id: number;
        };
        query: {
          /** Number of matches to limit to */
          limit?: number;
          /** Number of matches to offset start by */
          offset?: number;
          /** Whether the player won */
          win?: number;
          /** Patch ID */
          patch?: number;
          /** Game Mode ID */
          game_mode?: number;
          /** Lobby type ID */
          lobby_type?: number;
          /** Region ID */
          region?: number;
          /** Days previous */
          date?: number;
          /** Lane Role ID */
          lane_role?: number;
          /** Hero ID */
          hero_id?: number;
          /** Whether the player was radiant */
          is_radiant?: number;
          /** Account IDs in the match (array) */
          included_account_id?: number;
          /** Account IDs not in the match (array) */
          excluded_account_id?: number;
          /** Hero IDs on the player's team (array) */
          with_hero_id?: number;
          /** Hero IDs against the player's team (array) */
          against_hero_id?: number;
          /** Whether the match was significant for aggregation purposes. Defaults to 1 (true), set this to 0 to return data for non-standard modes/matches. */
          significant?: number;
          /** The minimum number of games played, for filtering hero stats */
          having?: number;
          /** The field to return matches sorted by in descending order */
          sort?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** Integer describing whether or not the player left the game. 0: didn't leave. 1: left safely. 2+: Abandoned */
            leaver_status?: { [key: string]: unknown };
            /** Integer corresponding to game mode played. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/game_mode.json */
            game_mode?: { [key: string]: unknown };
            /** Integer corresponding to lobby type of match. List of constants can be found here: https://github.com/odota/dotaconstants/blob/master/json/lobby_type.json */
            lobby_type?: { [key: string]: unknown };
            /** lane_role */
            lane_role?: { [key: string]: unknown };
            /** Integer corresponding to the region the game was played on */
            region?: { [key: string]: unknown };
            /** patch */
            patch?: { [key: string]: unknown };
          };
        };
      };
    };
  };
  "/players/{account_id}/histograms/{field}": {
    /** Distribution of matches in a single stat */
    get: {
      parameters: {
        path: {
          /** Steam32 account ID */
          account_id: number;
          /** Field to aggregate on */
          field: string;
        };
        query: {
          /** Number of matches to limit to */
          limit?: number;
          /** Number of matches to offset start by */
          offset?: number;
          /** Whether the player won */
          win?: number;
          /** Patch ID */
          patch?: number;
          /** Game Mode ID */
          game_mode?: number;
          /** Lobby type ID */
          lobby_type?: number;
          /** Region ID */
          region?: number;
          /** Days previous */
          date?: number;
          /** Lane Role ID */
          lane_role?: number;
          /** Hero ID */
          hero_id?: number;
          /** Whether the player was radiant */
          is_radiant?: number;
          /** Account IDs in the match (array) */
          included_account_id?: number;
          /** Account IDs not in the match (array) */
          excluded_account_id?: number;
          /** Hero IDs on the player's team (array) */
          with_hero_id?: number;
          /** Hero IDs against the player's team (array) */
          against_hero_id?: number;
          /** Whether the match was significant for aggregation purposes. Defaults to 1 (true), set this to 0 to return data for non-standard modes/matches. */
          significant?: number;
          /** The minimum number of games played, for filtering hero stats */
          having?: number;
          /** The field to return matches sorted by in descending order */
          sort?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: { [key: string]: unknown }[];
        };
      };
    };
  };
  "/players/{account_id}/wardmap": {
    /** Wards placed in matches played */
    get: {
      parameters: {
        path: {
          /** Steam32 account ID */
          account_id: number;
        };
        query: {
          /** Number of matches to limit to */
          limit?: number;
          /** Number of matches to offset start by */
          offset?: number;
          /** Whether the player won */
          win?: number;
          /** Patch ID */
          patch?: number;
          /** Game Mode ID */
          game_mode?: number;
          /** Lobby type ID */
          lobby_type?: number;
          /** Region ID */
          region?: number;
          /** Days previous */
          date?: number;
          /** Lane Role ID */
          lane_role?: number;
          /** Hero ID */
          hero_id?: number;
          /** Whether the player was radiant */
          is_radiant?: number;
          /** Account IDs in the match (array) */
          included_account_id?: number;
          /** Account IDs not in the match (array) */
          excluded_account_id?: number;
          /** Hero IDs on the player's team (array) */
          with_hero_id?: number;
          /** Hero IDs against the player's team (array) */
          against_hero_id?: number;
          /** Whether the match was significant for aggregation purposes. Defaults to 1 (true), set this to 0 to return data for non-standard modes/matches. */
          significant?: number;
          /** The minimum number of games played, for filtering hero stats */
          having?: number;
          /** The field to return matches sorted by in descending order */
          sort?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** obs */
            obs?: { [key: string]: unknown };
            /** sen */
            sen?: { [key: string]: unknown };
          };
        };
      };
    };
  };
  "/players/{account_id}/wordcloud": {
    /** Words said/read in matches played */
    get: {
      parameters: {
        path: {
          /** Steam32 account ID */
          account_id: number;
        };
        query: {
          /** Number of matches to limit to */
          limit?: number;
          /** Number of matches to offset start by */
          offset?: number;
          /** Whether the player won */
          win?: number;
          /** Patch ID */
          patch?: number;
          /** Game Mode ID */
          game_mode?: number;
          /** Lobby type ID */
          lobby_type?: number;
          /** Region ID */
          region?: number;
          /** Days previous */
          date?: number;
          /** Lane Role ID */
          lane_role?: number;
          /** Hero ID */
          hero_id?: number;
          /** Whether the player was radiant */
          is_radiant?: number;
          /** Account IDs in the match (array) */
          included_account_id?: number;
          /** Account IDs not in the match (array) */
          excluded_account_id?: number;
          /** Hero IDs on the player's team (array) */
          with_hero_id?: number;
          /** Hero IDs against the player's team (array) */
          against_hero_id?: number;
          /** Whether the match was significant for aggregation purposes. Defaults to 1 (true), set this to 0 to return data for non-standard modes/matches. */
          significant?: number;
          /** The minimum number of games played, for filtering hero stats */
          having?: number;
          /** The field to return matches sorted by in descending order */
          sort?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** my_word_counts */
            my_word_counts?: { [key: string]: unknown };
            /** all_word_counts */
            all_word_counts?: { [key: string]: unknown };
          };
        };
      };
    };
  };
  "/players/{account_id}/ratings": {
    /** Player rating history */
    get: {
      parameters: {
        path: {
          /** Steam32 account ID */
          account_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** account_id */
            account_id?: number;
            /** match_id */
            match_id?: number;
            /** solo_competitive_rank */
            solo_competitive_rank?: number;
            /** competitive_rank */
            competitive_rank?: number;
            /** time */
            time?: number;
          }[];
        };
      };
    };
  };
  "/players/{account_id}/rankings": {
    /** Player hero rankings */
    get: {
      parameters: {
        path: {
          /** Steam32 account ID */
          account_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** The ID value of the hero played */
            hero_id?: string;
            /** percent_rank */
            rank?: number;
            /** numeric_rank */
            card?: number;
          }[];
        };
      };
    };
  };
  "/players/{account_id}/refresh": {
    /** Refresh player match history */
    post: {
      parameters: {
        path: {
          /** Steam32 account ID */
          account_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/proPlayers": {
    /** Get list of pro players */
    get: {
      responses: {
        /** Success */
        200: {
          schema: {
            /** Player's account identifier */
            account_id?: number;
            /** Player's steam identifier */
            steamid?: string;
            /** Steam picture URL (small picture) */
            avatar?: string;
            /** Steam picture URL (medium picture) */
            avatarmedium?: string;
            /** Steam picture URL (full picture) */
            avatarfull?: string;
            /** Steam profile URL */
            profileurl?: string;
            /** Player's Steam name */
            personaname?: string;
            /** Date and time of last login to OpenDota */
            last_login?: string;
            /** Date and time of last request to refresh player's match history */
            full_history_time?: string;
            /** Amount of dollars the player has donated to OpenDota */
            cheese?: number;
            /** Whether the refresh of player' match history failed */
            fh_unavailable?: boolean;
            /** Player's country identifier, e.g. US */
            loccountrycode?: string;
            /** Verified player name, e.g. 'Miracle-' */
            name?: string;
            /** Player's country code */
            country_code?: string;
            /** Player's ingame role (core: 1 or support: 2) */
            fantasy_role?: number;
            /** Player's team identifier */
            team_id?: number;
            /** Player's team name, e.g. 'Evil Geniuses' */
            team_name?: string;
            /** Player's team shorthand tag, e.g. 'EG' */
            team_tag?: string;
            /** Whether the roster lock is active */
            is_locked?: boolean;
            /** Whether the player is professional or not */
            is_pro?: boolean;
            /** When the roster lock will end */
            locked_until?: number;
          }[];
        };
      };
    };
  };
  "/proMatches": {
    /** Get list of pro matches */
    get: {
      parameters: {
        query: {
          /** Get matches with a match ID lower than this value */
          less_than_match_id?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** Used to identify individual matches, e.g. 3703866531 */
            match_id?: number;
            /** Length of the match */
            duration?: number;
            /** Unix timestamp of when the match began */
            start_time?: number;
            /** The Radiant's team_id */
            radiant_team_id?: number;
            /** The Radiant's team name */
            radiant_name?: string;
            /** The Dire's team_id */
            dire_team_id?: number;
            /** The Dire's team name */
            dire_name?: string;
            /** Identifier for the league the match took place in */
            leagueid?: number;
            /** Name of league the match took place in */
            league_name?: string;
            /** Identifier for the series of the match */
            series_id?: number;
            /** Type of series the match was */
            series_type?: number;
            /** Number of kills the Radiant team had when the match ended */
            radiant_score?: number;
            /** Number of kills the Dire team had when the match ended */
            dire_score?: number;
            /** Whether or not the Radiant won the match */
            radiant_win?: boolean;
            /** Whether the team/player/hero was on Radiant */
            radiant?: boolean;
          }[];
        };
      };
    };
  };
  "/publicMatches": {
    /** Get list of randomly sampled public matches */
    get: {
      parameters: {
        query: {
          /** Order by MMR ascending */
          mmr_ascending?: number;
          /** Order by MMR descending */
          mmr_descending?: number;
          /** Get matches with a match ID lower than this value */
          less_than_match_id?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** match_id */
            match_id?: number;
            /** match_seq_num */
            match_seq_num?: number;
            /** Boolean indicating whether Radiant won the match */
            radiant_win?: boolean;
            /** start_time */
            start_time?: number;
            /** Duration of the game in seconds */
            duration?: number;
            /** radiant_team */
            radiant_team?: string;
            /** dire_team */
            dire_team?: string;
          }[];
        };
      };
    };
  };
  "/parsedMatches": {
    /** Get list of parsed match IDs */
    get: {
      parameters: {
        query: {
          /** Get matches with a match ID lower than this value */
          less_than_match_id?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** match_id */
            match_id?: number;
          }[];
        };
      };
    };
  };
  "/explorer": {
    /** Submit arbitrary SQL queries to the database */
    get: {
      parameters: {
        query: {
          /** The PostgreSQL query as percent-encoded string. */
          sql?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/metadata": {
    /** Site metadata */
    get: {
      responses: {
        /** Success */
        200: {
          schema: {
            /** banner */
            banner?: { [key: string]: unknown };
            /** cheese */
            cheese?: {
              /** cheese */
              cheese?: string;
              /** goal */
              goal?: string;
            };
          };
        };
      };
    };
  };
  "/distributions": {
    /** Distributions of MMR data by bracket and country */
    get: {
      responses: {
        /** Success */
        200: {
          schema: {
            /** ranks */
            ranks?: {
              /** command */
              commmand?: string;
              /** rowCount */
              rowCount?: number;
              /** rows */
              rows?: {
                /** bin */
                bin?: number;
                /** bin_name */
                bin_name?: number;
                /** count */
                count?: number;
                /** cumulative_sum */
                cumulative_sum?: number;
              }[];
              /** fields */
              fields?: {
                /** name */
                name?: string;
                /** tableID */
                tableID?: number;
                /** columnID */
                columnID?: number;
                /** dataTypeID */
                dataTypeID?: number;
                /** dataTypeSize */
                dataTypeSize?: number;
                /** dataTypeModifier */
                dataTypeModifier?: string;
                /** format */
                format?: string;
              }[];
              /** rowAsArray */
              rowAsArray?: boolean;
              /** sum */
              sum?: {
                /** count */
                count?: number;
              };
            };
            /** mmr */
            mmr?: {
              /** command */
              commmand?: string;
              /** rowCount */
              rowCount?: number;
              /** rows */
              rows?: {
                /** bin */
                bin?: number;
                /** bin_name */
                bin_name?: number;
                /** count */
                count?: number;
                /** cumulative_sum */
                cumulative_sum?: number;
              }[];
              /** fields */
              fields?: {
                /** name */
                name?: string;
                /** tableID */
                tableID?: number;
                /** columnID */
                columnID?: number;
                /** dataTypeID */
                dataTypeID?: number;
                /** dataTypeSize */
                dataTypeSize?: number;
                /** dataTypeModifier */
                dataTypeModifier?: string;
                /** format */
                format?: string;
              }[];
              /** rowAsArray */
              rowAsArray?: boolean;
              /** sum */
              sum?: {
                /** count */
                count?: number;
              };
            };
            /** country_mmr */
            country_mmr?: {
              /** command */
              commmand?: string;
              /** rowCount */
              rowCount?: number;
              /** rows */
              rows?: {
                /** loccountrycode */
                loccountrycode?: string;
                /** count */
                count?: number;
                /** avg */
                avg?: string;
                /** common */
                common?: string;
              }[];
              /** fields */
              fields?: {
                /** name */
                name?: string;
                /** tableID */
                tableID?: number;
                /** columnID */
                columnID?: number;
                /** dataTypeID */
                dataTypeID?: number;
                /** dataTypeSize */
                dataTypeSize?: number;
                /** dataTypeModifier */
                dataTypeModifier?: number;
                /** format */
                format?: string;
              }[];
              /** rowAsArray */
              rowAsArray?: boolean;
            };
          };
        };
      };
    };
  };
  "/search": {
    /** Search players by personaname. */
    get: {
      parameters: {
        query: {
          /** Search string */
          q: string;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** account_id */
            account_id?: number;
            /** avatarfull */
            avatarfull?: string;
            /** personaname */
            personaname?: string;
            /** last_match_time. May not be present or null. */
            last_match_time?: string;
            /** similarity */
            similarity?: number;
          }[];
        };
      };
    };
  };
  "/rankings": {
    /** Top players by hero */
    get: {
      parameters: {
        query: {
          /** Hero ID */
          hero_id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** The ID value of the hero played */
            hero_id?: number;
            /** rankings */
            rankings?: {
              /** account_id */
              account_id?: number;
              /** score */
              score?: string;
              /** steamid */
              steamid?: string;
              /** avatar */
              avatar?: string;
              /** avatarmedium */
              avatarmedium?: string;
              /** avatarfull */
              avatarfull?: string;
              /** profileurl */
              profileurl?: string;
              /** personaname */
              personaname?: string;
              /** last_login */
              last_login?: string;
              /** full_history_time */
              full_history_time?: string;
              /** cheese */
              cheese?: number;
              /** fh_unavailable */
              fh_unavailable?: boolean;
              /** loccountrycode */
              loccountrycode?: string;
              /** rank_tier */
              rank_tier?: number;
            };
          };
        };
      };
    };
  };
  "/benchmarks": {
    /** Benchmarks of average stat values for a hero */
    get: {
      parameters: {
        query: {
          /** Hero ID */
          hero_id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** The ID value of the hero played */
            hero_id?: number;
            /** result */
            result?: {
              gold_per_min?: {
                /** percentile */
                percentile?: number;
                /** value */
                value?: number;
              }[];
              xp_per_min?: {
                /** percentile */
                percentile?: number;
                /** value */
                value?: number;
              }[];
              kills_per_min?: {
                /** percentile */
                percentile?: number;
                /** value */
                value?: number;
              }[];
              last_hits_per_min?: {
                /** percentile */
                percentile?: number;
                /** value */
                value?: number;
              }[];
              hero_damage_per_min?: {
                /** percentile */
                percentile?: number;
                /** value */
                value?: number;
              }[];
              hero_healing_per_min?: {
                /** percentile */
                percentile?: number;
                /** value */
                value?: number;
              }[];
              tower_damage?: {
                /** percentile */
                percentile?: number;
                /** value */
                value?: number;
              }[];
            };
          };
        };
      };
    };
  };
  "/status": {
    /** Get current service statistics */
    get: {
      responses: {
        /** Success */
        200: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/health": {
    /** Get service health data */
    get: {
      responses: {
        /** Success */
        200: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/request/{jobId}": {
    /** Get parse request state */
    get: {
      parameters: {
        path: {
          /** The job ID to query. */
          jobId: string;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/request/{match_id}": {
    /** Submit a new parse request */
    post: {
      parameters: {
        path: {
          match_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/findMatches": {
    /** Finds recent matches by heroes played */
    get: {
      parameters: {
        query: {
          /** Hero IDs on first team (array) */
          teamA?: number;
          /** Hero IDs on second team (array) */
          teamB?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/heroes": {
    /** Get hero data */
    get: {
      responses: {
        /** Success */
        200: {
          schema: {
            /** Numeric identifier for the hero object */
            id?: number;
            /** Dota hero command name, e.g. 'npc_dota_hero_antimage' */
            name?: string;
            /** Hero name, e.g. 'Anti-Mage' */
            localized_name?: string;
            /** Hero primary shorthand attribute name, e.g. 'agi' */
            primary_attr?: string;
            /** Hero attack type, either 'Melee' or 'Ranged' */
            attack_type?: string;
            roles?: string[];
          }[];
        };
      };
    };
  };
  "/heroStats": {
    /** Get stats about hero performance in recent matches */
    get: {
      parameters: {};
      responses: {
        /** Success */
        200: {
          schema: {
            /** id */
            id?: number;
            /** name */
            name?: string;
            /** localized_name */
            localized_name?: string;
            /** img */
            img?: string;
            /** icon */
            icon?: string;
            /** pro_win */
            pro_win?: number;
            /** pro_pick */
            pro_pick?: number;
            /** The ID value of the hero played */
            hero_id?: number;
            /** pro_ban */
            pro_ban?: number;
            /** Herald picks */
            "1_pick"?: number;
            /** Herald wins */
            "1_win"?: number;
            /** Guardian picks */
            "2_pick"?: number;
            /** Guardian wins */
            "2_win"?: number;
            /** Crusader picks */
            "3_pick"?: number;
            /** Crusader wins */
            "3_win"?: number;
            /** Archon picks */
            "4_pick"?: number;
            /** Archon wins */
            "4_win"?: number;
            /** Legend picks */
            "5_pick"?: number;
            /** Legend wins */
            "5_win"?: number;
            /** Ancient picks */
            "6_pick"?: number;
            /** Ancient wins */
            "6_win"?: number;
            /** Divine picks */
            "7_pick"?: number;
            /** Divine wins */
            "7_win"?: number;
            /** Immortal picks */
            "8_pick"?: number;
            /** Immortal wins */
            "8_win"?: number;
            /** Picks in Turbo mode this month */
            turbo_pick?: number;
            /** Wins in Turbo mode this month */
            turbo_win?: number;
          }[];
        };
      };
    };
  };
  "/heroes/{hero_id}/matches": {
    /** Get recent matches with a hero */
    get: {
      parameters: {
        path: {
          /** Hero ID */
          hero_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** Used to identify individual matches, e.g. 3703866531 */
            match_id?: number;
            /** Length of the match */
            duration?: number;
            /** Unix timestamp of when the match began */
            start_time?: number;
            /** The Radiant's team_id */
            radiant_team_id?: number;
            /** The Radiant's team name */
            radiant_name?: string;
            /** The Dire's team_id */
            dire_team_id?: number;
            /** The Dire's team name */
            dire_name?: string;
            /** Identifier for the league the match took place in */
            leagueid?: number;
            /** Name of league the match took place in */
            league_name?: string;
            /** Identifier for the series of the match */
            series_id?: number;
            /** Type of series the match was */
            series_type?: number;
            /** Number of kills the Radiant team had when the match ended */
            radiant_score?: number;
            /** Number of kills the Dire team had when the match ended */
            dire_score?: number;
            /** Whether or not the Radiant won the match */
            radiant_win?: boolean;
            /** Whether the team/player/hero was on Radiant */
            radiant?: boolean;
          }[];
        };
      };
    };
  };
  "/heroes/{hero_id}/matchups": {
    /** Get results against other heroes for a hero */
    get: {
      parameters: {
        path: {
          /** Hero ID */
          hero_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** Numeric identifier for the hero object */
            hero_id?: number;
            /** Number of games played */
            games_played?: number;
            /** Number of games won */
            wins?: number;
          }[];
        };
      };
    };
  };
  "/heroes/{hero_id}/durations": {
    /** Get hero performance over a range of match durations */
    get: {
      parameters: {
        path: {
          /** Hero ID */
          hero_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** Lower bound of number of seconds the match lasted */
            duration_bin?: string;
            /** Number of games played */
            games_played?: number;
            /** Number of wins */
            wins?: number;
          }[];
        };
      };
    };
  };
  "/heroes/{hero_id}/players": {
    /** Get players who have played this hero */
    get: {
      parameters: {
        path: {
          /** Hero ID */
          hero_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** Player's account identifier */
            account_id?: number;
            /** Player's steam identifier */
            steamid?: string;
            /** Steam picture URL (small picture) */
            avatar?: string;
            /** Steam picture URL (medium picture) */
            avatarmedium?: string;
            /** Steam picture URL (full picture) */
            avatarfull?: string;
            /** Steam profile URL */
            profileurl?: string;
            /** Player's Steam name */
            personaname?: string;
            /** Date and time of last login to OpenDota */
            last_login?: string;
            /** Date and time of last request to refresh player's match history */
            full_history_time?: string;
            /** Amount of dollars the player has donated to OpenDota */
            cheese?: number;
            /** Whether the refresh of player' match history failed */
            fh_unavailable?: boolean;
            /** Player's country identifier, e.g. US */
            loccountrycode?: string;
            /** Verified player name, e.g. 'Miracle-' */
            name?: string;
            /** Player's country code */
            country_code?: string;
            /** Player's ingame role (core: 1 or support: 2) */
            fantasy_role?: number;
            /** Player's team identifier */
            team_id?: number;
            /** Player's team name, e.g. 'Evil Geniuses' */
            team_name?: string;
            /** Player's team shorthand tag, e.g. 'EG' */
            team_tag?: string;
            /** Whether the roster lock is active */
            is_locked?: boolean;
            /** Whether the player is professional or not */
            is_pro?: boolean;
            /** When the roster lock will end */
            locked_until?: number;
          }[][];
        };
      };
    };
  };
  "/heroes/{hero_id}/itemPopularity": {
    /** Get item popularity of hero categoried by start, early, mid and late game, analyzed from professional games */
    get: {
      parameters: {
        path: {
          /** Hero ID */
          hero_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** Items bought before game started */
            start_game_items?: {
              /** Number of item bought */
              item?: number;
            };
            /** Items bought in the first 10 min of the game, with cost at least 700 */
            early_game_items?: {
              /** Number of item bought */
              item?: number;
            };
            /** Items bought between 10 and 25 min of the game, with cost at least 2000 */
            mid_game_items?: {
              /** Number of item bought */
              item?: number;
            };
            /** Items bought at least 25 min after game started, with cost at least 4000 */
            late_game_items?: {
              /** Number of item bought */
              item?: number;
            };
          };
        };
      };
    };
  };
  "/leagues": {
    /** Get league data */
    get: {
      responses: {
        /** Success */
        200: {
          schema: {
            /** leagueid */
            leagueid?: number;
            /** ticket */
            ticket?: string;
            /** banner */
            banner?: string;
            /** tier */
            tier?: string;
            /** name */
            name?: string;
          }[];
        };
      };
    };
  };
  "/leagues/{league_id}": {
    /** Get data for a league */
    get: {
      parameters: {
        path: {
          /** League ID */
          league_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** leagueid */
            leagueid?: number;
            /** ticket */
            ticket?: string;
            /** banner */
            banner?: string;
            /** tier */
            tier?: string;
            /** name */
            name?: string;
          }[];
        };
      };
    };
  };
  "/leagues/{league_id}/matches": {
    /** Get matches for a team */
    get: {
      parameters: {
        path: {
          /** League ID */
          league_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** Used to identify individual matches, e.g. 3703866531 */
            match_id?: number;
            /** Length of the match */
            duration?: number;
            /** Unix timestamp of when the match began */
            start_time?: number;
            /** The Radiant's team_id */
            radiant_team_id?: number;
            /** The Radiant's team name */
            radiant_name?: string;
            /** The Dire's team_id */
            dire_team_id?: number;
            /** The Dire's team name */
            dire_name?: string;
            /** Identifier for the league the match took place in */
            leagueid?: number;
            /** Name of league the match took place in */
            league_name?: string;
            /** Identifier for the series of the match */
            series_id?: number;
            /** Type of series the match was */
            series_type?: number;
            /** Number of kills the Radiant team had when the match ended */
            radiant_score?: number;
            /** Number of kills the Dire team had when the match ended */
            dire_score?: number;
            /** Whether or not the Radiant won the match */
            radiant_win?: boolean;
            /** Whether the team/player/hero was on Radiant */
            radiant?: boolean;
          };
        };
      };
    };
  };
  "/leagues/{league_id}/teams": {
    /** Get teams for a league */
    get: {
      parameters: {
        path: {
          /** League ID */
          league_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** Team's identifier */
            team_id?: number;
            /** The Elo rating of the team */
            rating?: number;
            /** The number of games won by this team */
            wins?: number;
            /** The number of losses by this team */
            losses?: number;
            /** The Unix timestamp of the last match played by this team */
            last_match_time?: number;
            /** Team name, eg. 'Newbee' */
            name?: string;
            /** The team tag/abbreviation */
            tag?: string;
          };
        };
      };
    };
  };
  "/teams": {
    /** Get team data */
    get: {
      responses: {
        /** Success */
        200: {
          schema: {
            /** Team's identifier */
            team_id?: number;
            /** The Elo rating of the team */
            rating?: number;
            /** The number of games won by this team */
            wins?: number;
            /** The number of losses by this team */
            losses?: number;
            /** The Unix timestamp of the last match played by this team */
            last_match_time?: number;
            /** Team name, eg. 'Newbee' */
            name?: string;
            /** The team tag/abbreviation */
            tag?: string;
          }[];
        };
      };
    };
  };
  "/teams/{team_id}": {
    /** Get data for a team */
    get: {
      parameters: {
        path: {
          /** Team ID */
          team_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** Team's identifier */
            team_id?: number;
            /** The Elo rating of the team */
            rating?: number;
            /** The number of games won by this team */
            wins?: number;
            /** The number of losses by this team */
            losses?: number;
            /** The Unix timestamp of the last match played by this team */
            last_match_time?: number;
            /** Team name, eg. 'Newbee' */
            name?: string;
            /** The team tag/abbreviation */
            tag?: string;
          };
        };
      };
    };
  };
  "/teams/{team_id}/matches": {
    /** Get matches for a team */
    get: {
      parameters: {
        path: {
          /** Team ID */
          team_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** Used to identify individual matches, e.g. 3703866531 */
            match_id?: number;
            /** Length of the match */
            duration?: number;
            /** Unix timestamp of when the match began */
            start_time?: number;
            /** The Radiant's team_id */
            radiant_team_id?: number;
            /** The Radiant's team name */
            radiant_name?: string;
            /** The Dire's team_id */
            dire_team_id?: number;
            /** The Dire's team name */
            dire_name?: string;
            /** Identifier for the league the match took place in */
            leagueid?: number;
            /** Name of league the match took place in */
            league_name?: string;
            /** Identifier for the series of the match */
            series_id?: number;
            /** Type of series the match was */
            series_type?: number;
            /** Number of kills the Radiant team had when the match ended */
            radiant_score?: number;
            /** Number of kills the Dire team had when the match ended */
            dire_score?: number;
            /** Whether or not the Radiant won the match */
            radiant_win?: boolean;
            /** Whether the team/player/hero was on Radiant */
            radiant?: boolean;
          };
        };
      };
    };
  };
  "/teams/{team_id}/players": {
    /** Get players who have played for a team */
    get: {
      parameters: {
        path: {
          /** Team ID */
          team_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** The player account ID */
            account_id?: string;
            /** The player name */
            name?: string;
            /** Number of games played */
            games_played?: number;
            /** Number of wins */
            wins?: number;
            /** If this player is on the current roster */
            is_current_team_member?: boolean;
          };
        };
      };
    };
  };
  "/teams/{team_id}/heroes": {
    /** Get heroes for a team */
    get: {
      parameters: {
        path: {
          /** Team ID */
          team_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** The hero ID */
            hero_id?: number;
            /** The hero name */
            name?: string;
            /** Number of games played */
            games_played?: number;
            /** Number of wins */
            wins?: number;
          };
        };
      };
    };
  };
  "/replays": {
    /** Get data to construct a replay URL with */
    get: {
      parameters: {
        query: {
          /** Match IDs (array) */
          match_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** match_id */
            match_id?: number;
            /** cluster */
            cluster?: number;
            /** replay_salt */
            replay_salt?: number;
          }[];
        };
      };
    };
  };
  "/records/{field}": {
    /** Get top performances in a stat */
    get: {
      parameters: {
        path: {
          /** Field name to query */
          field: string;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** match_id */
            match_id?: number;
            /** start_time */
            start_time?: number;
            /** The ID value of the hero played */
            hero_id?: number;
            /** score */
            score?: number;
          }[];
        };
      };
    };
  };
  "/live": {
    /** Get top currently ongoing live games */
    get: {
      parameters: {};
      responses: {
        /** Success */
        200: {
          schema: { [key: string]: unknown }[];
        };
      };
    };
  };
  "/scenarios/itemTimings": {
    /** Win rates for certain item timings on a hero for items that cost at least 1400 gold */
    get: {
      parameters: {
        query: {
          /** Filter by item name e.g. "spirit_vessel" */
          item?: string;
          /** Hero ID */
          hero_id?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** Hero ID */
            hero_id?: number;
            /** Purchased item */
            item?: string;
            /** Ingame time in seconds before the item was purchased */
            time?: number;
            /** The number of games where the hero bought this item before this time */
            games?: string;
            /** The number of games won where the hero bought this item before this time */
            wins?: string;
          }[];
        };
      };
    };
  };
  "/scenarios/laneRoles": {
    /** Win rates for heroes in certain lane roles */
    get: {
      parameters: {
        query: {
          /** Filter by lane role 1-4 (Safe, Mid, Off, Jungle) */
          lane_role?: string;
          /** Hero ID */
          hero_id?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** Hero ID */
            hero_id?: number;
            /** The hero's lane role */
            lane_role?: number;
            /** Maximum game length in seconds */
            time?: number;
            /** The number of games where the hero played in this lane role */
            games?: string;
            /** The number of games won where the hero played in this lane role */
            wins?: string;
          }[];
        };
      };
    };
  };
  "/scenarios/misc": {
    /** Miscellaneous team scenarios */
    get: {
      parameters: {
        query: {
          /** pos_chat_1min,neg_chat_1min,courier_kill,first_blood */
          scenario?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: {
            /** The scenario's name or description */
            scenario?: string;
            /** Boolean indicating whether Radiant executed this scenario */
            is_radiant?: boolean;
            /** Region the game was played in */
            region?: number;
            /** The number of games where this scenario occurred */
            games?: string;
            /** The number of games won where this scenario occured */
            wins?: string;
          }[];
        };
      };
    };
  };
  "/schema": {
    /** Get database schema */
    get: {
      parameters: {};
      responses: {
        /** Success */
        200: {
          schema: {
            /** table_name */
            table_name?: string;
            /** column_name */
            column_name?: string;
            /** data_type */
            data_type?: string;
          }[];
        };
      };
    };
  };
  "/constants/{resource}": {
    /** Get static game data mirrored from the dotaconstants repository. */
    get: {
      parameters: {
        path: {
          /** Resource name e.g. `heroes`. [List of resources](https://github.com/odota/dotaconstants/tree/master/build) */
          resource: string;
        };
      };
      responses: {
        /** Success */
        200: {
          schema: { [key: string]: unknown }[];
        };
      };
    };
  };
  "/constants": {
    /** Gets an array of available resources. */
    get: {
      parameters: {};
      responses: {
        /** Success */
        200: {
          schema: string[];
        };
      };
    };
  };
}

export interface operations {}

export interface external {}
